title: 公共數位創新空間
author: PDIS
email: hello@pdis.tw
description: > # this means to ignore newlines until "baseurl:"
  這是一個 PDIS 的官方網站，而且目前什麼都還沒有。

twitter_username: TaiwanPDIS
github_username:  pdis
permalink: pretty

collections: # create posts folder other than _posts
  projects:
    output: true
    permalink: /:collection/:path/
  tracks:
    output: true
    permalink: /:collection/:path/

sass:
    style: compressed
