title: 公共數位創新空間
author: PDIS
email: hello@pdis.tw
description: > # this means to ignore newlines until "baseurl:"
  A Site of PDIS

baseurl: '/'
twitter_username: TaiwanPDIS
github_username:  pdis

collections: # create posts folder other than _posts
  projects:
    output: true
    permalink: /:collection/:path/

sass:
    style: compressed
