title:   行⁠政⁠院公⁠共⁠數⁠位創⁠新⁠空⁠間
author: PDIS
email: hello@pdis.tw
lang: zh-tw
description: > # this means to ignore newlines until "baseurl:"
  我⁠們協⁠助政⁠府⁠部⁠會提⁠升數⁠位⁠服⁠務⁠品⁠質。

image: /images/pdis-team.jpg
twitter_username: TaiwanPDIS
github_username:  pdis
permalink: pretty

collections: # create posts folder other than _posts
  projects:
    output: true
    permalink: /:collection/:path/
  tracks:
    output: true
    permalink: /:collection/:path/

sass:
    style: compressed
