title: Starter Template
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

baseurl: '/'
twitter_username: TaiwanPDIS
github_username:  pdis

sass:
    style: compressed
